20-rails-validations/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :statuses, :reactions
  resources :status_reactions, only: [:new, :create]
end

20-rails-validations/app/models/reaction.rb
class Reaction < ApplicationRecord
  # has_many :status_reactions, dependent: :destroy
  # has_many :statuses, through: :status_reactions


  validates :emoji, uniqueness: true, presence: true
  # validates_uniqueness_of :emoji

  def emoji_a_lot
    self.emoji * 10
  end
end

20-rails-validations/app/models/status.rb
class Status < ApplicationRecord

  # validates :body, presence: true
  # validates_presence_of :body
  # validates :body, numeric: {}
  validates_length_of :body, minimum: 1, maximum: 160

  # validate :graham_must_be_mentioned

  has_many :status_reactions, dependent: :destroy
  has_many :reactions, through: :status_reactions


  private

  def graham_must_be_mentioned
    unless body.include? "Graham"
      errors.add(:body, "must include Graham's name!!!!!!")
    end
  end


end

20-rails-validations/app/models/status_reaction.rb
class StatusReaction < ApplicationRecord
  belongs_to :status
  belongs_to :reaction


  validates :reaction, uniqueness: { scope: :status
    #message: "should happen once per year" 
  }
end

20-rails-validations/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

20-rails-validations/app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController 

  def index
    @reactions = Reaction.all
  end

  def show
    @reaction = Reaction.find(params[:id])
  end

  def new
    @reaction = Reaction.new
  end

  def create
    @reaction = Reaction.create(reaction_params)
    if @reaction.valid?
      redirect_to @reaction
    else
      render :new
    end
  end

  def edit
    @reaction = Reaction.find(params[:id])
  end

  def update
    @reaction = Reaction.find(params[:id])
    if @reaction.update(reaction_params)
      redirect_to @reaction
    else
      render :edit
    end
  end

  def destroy
    Reaction.destroy(params[:id])
    redirect_to reactions_path
  end

  private

  def reaction_params
    params.require(:reaction).permit(:emoji)
  end

end

20-rails-validations/app/controllers/status_reactions_controller.rb
class StatusReactionsController < ApplicationController


  # def new
  #   @status_reaction = StatusReaction.new
  # end

  def create
    @status_reaction = StatusReaction.create(status_reaction_params)
    if @status_reaction.valid?
      redirect_to @status_reaction.status
    else
      render :new
    end
  end

  private

  def status_reaction_params
    params.require(:status_reaction).permit(:status_id, :reaction_id)
  end

end

20-rails-validations/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController 

  def index
    @statuses = Status.all
  end

  def show
    @status = Status.find(params[:id])
    @status_reaction = StatusReaction.new
    @reactions = Reaction.all
  end

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      # it worked!
      redirect_to @status
    else
      # invalid
      render :new
    end
  end

  def edit
    @status = Status.find(params[:id])
  end

  def update
    @status = Status.find(params[:id])
    if @status.update(status_params)
      redirect_to @status
    else
      render :edit
    end
  end

  def destroy
    Status.destroy(params[:id])
    redirect_to statuses_path
  end

  private

  def status_params
    params.require(:status).permit(:body)
  end

end

20-rails-validations/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reactions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

20-rails-validations/app/views/reactions/_form.erb
<% if @reaction.errors.any? %>
  <ul>
  <% @reaction.errors.full_messages.each do |error| %>
    <li>
    <%= error %>
    </li>
  <% end %>
  </ul>
<% end %>


<%= form_for @reaction do |f| %>
  <ul>
    <li>
      <%= f.label :emoji %>
      <%= f.text_field :emoji %>
    </li>
    <%= f.submit %>
  </ul>
  
<% end %>

20-rails-validations/app/views/reactions/edit.erb
<%= render "form" %>

20-rails-validations/app/views/reactions/index.erb
<h1>Index of reactions</h1>
<%= link_to "New reaction", new_reaction_path %>

<ol>
<% @reactions.each do |reaction| %>
  <li>
    <%= link_to reaction.emoji, reaction %>
  </li>
<% end %>
</ol>

20-rails-validations/app/views/reactions/new.erb
<%= render "form" %>

20-rails-validations/app/views/reactions/show.erb
<h1><%= @reaction.emoji %></h1>
<%= link_to "edit #{ @reaction.emoji }", edit_reaction_path(@reaction) %>
<%= form_for @reaction, method: :delete do |f| %>
  <%= f.submit "delete #{ @reaction.emoji }" %>
<% end %>

20-rails-validations/app/views/status_reactions/new.erb
<% if @status_reaction.errors.any? %>
  <ul>
  <% @status_reaction.errors.full_messages.each do |error| %>
    <li>
    <%= error %>
    </li>
  <% end %>
  </ul>
<% end %>


<%= form_for @status_reaction do |f| %>

<ul>
  <li>
    <%= f.label :status_id %>
<!--     <select name="status_id">
      <option value="1">🎆</option>
      <option value="2">🌘</option>
    </select> -->
    <%= f.collection_select :status_id, Status.all, :id, :body %>
  </li>
  <li>
    <%= f.label :reaction_id %>
    <%# f.text_field :reaction_id %>
    <%= f.collection_select :reaction_id, Reaction.all, :id, :emoji_a_lot %>
  </li>
</ul>

  <%= f.submit %>

<% end %>

20-rails-validations/app/views/statuses/_form.erb
<% if @status.errors.any? %>
  <ul>
  <% @status.errors.full_messages.each do |error| %>
    <li>
    <%= error %>
    </li>
  <% end %>
  </ul>
<% end %>


<%= form_for @status do |f| %>
  <ul>
    <li>
      <%= f.label :body %>
      <%= f.text_field :body %>
    </li>
  </ul>
  <%= f.submit %>
<% end %>

20-rails-validations/app/views/statuses/edit.erb
<%= render "form" %>

20-rails-validations/app/views/statuses/index.erb
<h1>Index of statuses</h1>
<%= link_to "New status", new_status_path %>
<ol>
<% @statuses.each do |status| %>
  <li>
    <%= link_to status.body, status %>
  </li>
<% end %>
</ol>

20-rails-validations/app/views/statuses/new.erb
<%= render "form" %>

20-rails-validations/app/views/statuses/show.erb
<h1><%= @status.body %></h1>

<%# @status.status_reactions.each do |status_reaction| %>
  <%#= status_reaction.reaction.emoji %>
<%# end %>

<% @status.reactions.each do |reaction| %>
  <%= reaction.emoji %>
<% end %>

<%= link_to "edit #{ @status.body }", edit_status_path(@status) %>
<%= form_for @status, method: :delete do |f| %>
  <%= f.submit "delete #{ @status.body }" %>
<% end %>


<%= form_for @status_reaction do |f| %>

<ul>
  <!-- <li> -->
    <%# f.label :status_id %>
<!--     <select name="status_id">
      <option value="1">🎆</option>
      <option value="2">🌘</option>
    </select> -->
    <%= f.hidden_field :status_id, value: @status.id %>
  <!-- </li> -->
  <li>
    <%= f.label :reaction_id %>
    <%# f.text_field :reaction_id %>
    <%= f.collection_select :reaction_id, @reactions, :id, :emoji_a_lot %>
  </li>
</ul>

  <%= f.submit %>

<% end %>