17-intro-to-rails/dogs-rails-scaffold/config/routes.rb
Rails.application.routes.draw do
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

17-intro-to-rails/dogs-rails-scaffold/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

17-intro-to-rails/dogs-rails-scaffold/app/models/dog.rb
class Dog < ApplicationRecord

  
end

17-intro-to-rails/dogs-rails-scaffold/app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :fluffiness)
    end
end

17-intro-to-rails/dogs-rails-scaffold/app/helpers/dogs_helper.rb
module DogsHelper
end

17-intro-to-rails/dogs-rails-scaffold/app/views/dogs/_form.html.erb
<%= form_with(model: dog, local: true) do |form| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :fluffiness %>
    <%= form.number_field :fluffiness %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

17-intro-to-rails/dogs-rails-scaffold/app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

17-intro-to-rails/dogs-rails-scaffold/app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fluffiness</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.fluffiness %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

17-intro-to-rails/dogs-rails-scaffold/app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

17-intro-to-rails/dogs-rails-scaffold/app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Fluffiness:</strong>
  <%= @dog.fluffiness %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>