18-rails-forms-crud/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "/dogs", to: "dogs#index"
  # get "/dogs/:id", to: "dogs#show", as: "dog"


  # resources :dogs, only: [:index, :show, :new, :create, :edit, :update]
  resources :dogs

  root "dogs#index"

end

18-rails-forms-crud/app/models/bone.rb
class Bone < ApplicationRecord
end

18-rails-forms-crud/app/models/dog.rb
class Dog < ApplicationRecord
end

18-rails-forms-crud/app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    if request.path != dogs_path
      redirect_to dogs_path
    end
    @dogs = Dog.all
    # render :sdhjkfakljshdflkhjasdf
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
    @dog.name = "Graham"
  end

  def create
    @dog = Dog.create(nested_dog_params)
    redirect_to @dog
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(nested_dog_params)
    redirect_to @dog
  end

  def destroy
    Dog.destroy(params[:id])
    redirect_to dogs_path
  end

  private

  def nested_dog_params
    params.require(:dog).permit(:name, :fluffiness)
  end

end

18-rails-forms-crud/app/views/dogs/_form.erb
<%= form_with model: @dog, local: true do |f| %>
  <ul>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <li>
      <%= f.label :fluffiness %>
      <%= f.number_field :fluffiness %>
    </li>
    <li>
      <%= f.label :color %>
      <%= f.text_field :color %>
    </li>
  </ul>

  <%= f.submit %>
<% end %>

18-rails-forms-crud/app/views/dogs/edit.erb
HELLO EDIT <%= @dog.name %>

<%= render partial: "form" %>

18-rails-forms-crud/app/views/dogs/index.erb
<ul>
<% @dogs.each do |pupper| %>
  <li>
    <!-- <a href="/dogs<"><%= pupper.name %></a> -->
<!--     <%= link_to pupper.name, "/dogs/#{ pupper.id }" %>
    <%= link_to pupper.name, dog_path(pupper.id) %>
    <%= link_to pupper.name, dog_path(pupper) %> -->
    <%= link_to pupper.name, pupper %>

    <%= form_for pupper, method: :delete do |f| %>
      <%= f.submit "DELETE" %>
    <% end %>

  </li>
<% end %>
</ul>

18-rails-forms-crud/app/views/dogs/new.erb
<%= render partial: "form" %>

18-rails-forms-crud/app/views/dogs/show.erb
<%= @dog.name %>
<%= @dog.fluffiness %>

18-rails-forms-crud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>